### PR TITLE
Fix windows-specific issues

### PR DESCRIPTION
**Pull request by Bear-03**
This PR goes in tandem with [this one in coqui-stt-sys](https://github.com/tazz4843/coqui-stt-sys/pull/2) to fix the same issues.

In that PR, new link attributes were added, so adding them manually in `build.rs` is not needed anymore.

Also, instead of adding `C:\stt` to the library search paths manually in `build.rs`, the same effect can be achieved by adding a library folder to the PATH env variable, which is the common solution to having global libraries on windows. If the developer doesn't want to change path, they can always create their own `build.rs` and add their own library search directory.

Lastly, as mentioned in the coqui-stt-sys PR, some bindings are not available on windows, so their high-level equivalents should also be removed.

### CODE REVIEW

**Comment by tazz4843** [comment]
Whoops sorry this took so long for me to see. This looks pretty good, I'll look into it closer once I get home in a few hours.

**Comment by Bear-03** [comment]
Awesome! By the way, I didn't do it myself because I wanted to discuss it with you, but maybe a README section talking about how to add the libraries on windows (PATH or custom search path in build.rs) would be a good idea.

Also, I wasn't able to test it on linux. I don't see why it wouldn't work, but it's best to test it just in case ;)

**Comment by tazz4843** [comment]
Hmm yeah that'd be a good idea. If you want to add some stuff to the README for Windows, that'd be great as well.

The checks themselves run on Linux runners and they seem to work fine, so it should work fine on Linux in general.

**Comment by tazz4843** [comment]
Just ran a Linux test, works fine. Let me know if you want to add the stuff to the README or not (for win), and I'll merge it.

**Comment by Bear-03** [comment]
Yup, I'll push a new commit when I get some time tomorrow.

**Comment by tazz4843** [comment]
Alright, thanks!

**Comment by Bear-03** [comment]
That should be it! Let me know if you want me to add or clarify anything :D

**Review by tazz4843 — APPROVED** [review]
lgtm

**Pull request merged**
